---
# defaults file for join_domain
chrony_config_server:
  - 192.168.86.97
chrony_config_logdir: /var/log/chrony
chrony_config_extra_options: {}
#
chrony_service_name: chronyd
chrony_config_location: /etc/chrony.conf
chrony_config_driftfile: /var/lib/chrony/drift
chrony_config_keyfile: /etc/chrony.keys
